server:
  port: 8083

spring:
  application:
    name: xpayment-adapter-app

  kafka:
    bootstrap-servers: localhost:9093

    producer:
      key-serializer:
        org.apache.kafka.common.serialization.StringSerializer
      value-serializer:
        org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: xpayment-adapter-result-consumers
      key-deserializer:
        org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer:
        org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: "com.learn.java.leonidm.xpaymentadapterapp.async.XPaymentAdapterRequestMessage"
    listener:
      ack-mode: manual
      concurrency: 1
      observation-enabled: true

    template:
      observation-enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

management:
  tracing:
    sampling:
      probability: 1.0 # 100% для отладки; в продакшн долженбыть меньше
    propagation:
      type: w3c,b3 # чтобы понимать и traceparent, и b3
    zipkin:
      tracing:
        endpoint: http://zipkin:9411/api/v2/spans
    server:
      port: 8081 # отдельный порт для Actuator
    endpoints:
      web:
        exposure:
          include: health # делаем health доступным через HTTP
    endpoint:
      health:
        probes:
          enabled: true # активируем разделение на liveness и readiness

app:
  kafka:
    topics:
      x-payment-adapter:
        request: xpayment-adapter.requests
        response: xpayment-adapter.responses

  x-payment-api:
    client:
      url: http://localhost:9999
      username: paymentAgentIprody
      password: iprodyTestPassword0123
      account: paymentAgentIprodyApiToken

  rabbitmq:
    exchange-name: payment-state-check-exchange
    queue-name: payment-state-check-queue
    max-retries: 60
    interval-ms: 10000